name: midori install test
on:
  workflow_dispatch:
  push:
env:
  VERSION: 11.5.2
  PACKAGE_AMD: midori_11.5.2-1_amd64.deb
  PACKAGE_ARM: midori_11.5.2-1_arm64.deb
jobs:
  install-ubuntu-lts:
    runs-on: ${{ matrix.os }}
    #runs-on: ${{ matrix.runner }} 
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-22.04
            arch: amd64
          - os: ubuntu-20.04
            arch: amd64  
#        runner: [ ubuntu-24.04, ubuntu-22.04, ubuntu-20.04 ]
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install wget
      - name: Get package
        run: | 
          wget https://github.com/goastian/midori-desktop/releases/download/v${VERSION}/${PACKAGE_AMD}
      - name: Install Midori
        run: |
          sudo apt install ./$PACKAGE        

  install-debian:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    strategy:
      matrix:
        container: ["debian:trixie","debian:12", "debian:11"]
    steps:
      - name: Install dependencies
        run: |
          apt update
      - name: install wget
        run: |
          apt install wget -y
      - name: Get package
        run: | 
          wget https://github.com/goastian/midori-desktop/releases/download/v$VERSION/$PACKAGE_AMD
      - name: Install Midori
        run: |
          apt install ./$PACKAGE -y
