name: midori install test
on:
  workflow_dispatch:
  push:
env:
  VERSION: 11.4.3
  PACKAGE: midori_11.4.3_amd64.deb
jobs:
  install-ubuntu-lts:
    runs-on: ${{ matrix.runner }} 
    strategy:
      matrix:
        runner: [ ubuntu-24.04, ubuntu-22.04, ubuntu-20.04 ]
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install wget
      - name: Get package
        run: | 
          wget https://github.com/goastian/midori-desktop/releases/download/v$VERSION/$PACKAGE
      - name: Install Midori
        run: |
          sudo apt install ./$PACKAGE        

  install-debian:
    runs-on: ubuntu-latest 
    container:
      image: debian:12
    steps:
      - name: Install dependencies
        run: |
          apt update -y
          apt install wget
      - name: Get package
        run: | 
          wget https://github.com/goastian/midori-desktop/releases/download/v$VERSION/$PACKAGE
      - name: Install Midori
        run: |
          apt install ./$PACKAGE
