name: midori install test
on:
  workflow_dispatch:
  push:
env:
  PACKAGE: midori_11.4.3_amd64.deb
jobs:
  install-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install wget
      - name: Get package
        run: | 
          wget https://github.com/goastian/midori-desktop/releases/download/v11.4.3/$PACKAGE
      - name: Install Midori
        run: |
          sudo apt install ./$PACKAGE
          
